name: Trigger nightly docker images build

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Call Docker Hub URL
      run: curl -X POST https://hub.docker.com/api/build/v1/source/e706feee-217a-40c9-b784-018f1b5594ed/trigger/37437530-0c1d-4e5e-9b7e-3da7720f34ca/call/
